/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Logo = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "logo.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type CtaBlock = {
  _type: "ctaBlock";
  heading?: string;
  subheading?: string;
  ctaLabel?: string;
  ctaUrl?: string;
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type TestimonialsBlock = {
  _type: "testimonialsBlock";
  heading?: string;
  testimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
};

export type CourseReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "course";
};

export type CoursesBlock = {
  _type: "coursesBlock";
  heading?: string;
  courses?: Array<
    {
      _key: string;
    } & CourseReference
  >;
};

export type DestinationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "destination";
};

export type DestinationsBlock = {
  _type: "destinationsBlock";
  heading?: string;
  destinations?: Array<
    {
      _key: string;
    } & DestinationReference
  >;
};

export type TimelineBlock = {
  _type: "timelineBlock";
  heading?: string;
  milestones?: Array<{
    year?: string;
    description?: string;
    _type: "milestone";
    _key: string;
  }>;
  futureVisionHeading?: string;
  futureVision?: string;
};

export type AboutBlock = {
  _type: "aboutBlock";
  heading?: string;
  mission?: string;
  vision?: string;
  whyFoundedHeading?: string;
  whyFounded?: string;
  coreValues?: Array<{
    title?: string;
    description?: string;
    _type: "coreValue";
    _key: string;
  }>;
};

export type TrustIndicatorsBlock = {
  _type: "trustIndicatorsBlock";
  heading?: string;
  trustLine?: string;
  stats?: Array<{
    value?: string;
    label?: string;
    _type: "trustStat";
    _key: string;
  }>;
  partnerLogos?: Array<{
    name?: string;
    logo?: Logo;
    _type: "partnerLogo";
    _key: string;
  }>;
  awards?: Array<string>;
  testimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
};

export type TrustBlock = {
  _type: "trustBlock";
  heading?: string;
  items?: Array<{
    title?: string;
    description?: string;
    _type: "trustItem";
    _key: string;
  }>;
};

export type Features = {
  _type: "features";
  heading?: string;
  items?: Array<{
    title?: string;
    description?: string;
    _type: "featureItem";
    _key: string;
  }>;
};

export type Hero = {
  _type: "hero";
  rotatingQuotes?: Array<string>;
  heading?: string;
  subheading?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ctaLabel?: string;
  ctaUrl?: string;
  secondaryCtaLabel?: string;
  secondaryCtaUrl?: string;
  tertiaryCtaLabel?: string;
  tertiaryCtaUrl?: string;
};

export type PageBuilder = Array<
  | ({
      _key: string;
    } & Hero)
  | ({
      _key: string;
    } & Features)
  | ({
      _key: string;
    } & TrustBlock)
  | ({
      _key: string;
    } & TrustIndicatorsBlock)
  | ({
      _key: string;
    } & AboutBlock)
  | ({
      _key: string;
    } & TimelineBlock)
  | ({
      _key: string;
    } & DestinationsBlock)
  | ({
      _key: string;
    } & CoursesBlock)
  | ({
      _key: string;
    } & TestimonialsBlock)
  | ({
      _key: string;
    } & CtaBlock)
>;

export type Lead = {
  _id: string;
  _type: "lead";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName?: string;
  email?: string;
  phone?: string;
  preferredCountry?: string;
  interestedCourse?: string;
  source?: string;
  status?: "New" | "Contacted" | "Converted" | "Closed";
  submittedAt?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  stats?: Array<{
    value?: string;
    label?: string;
    _type: "stat";
    _key: string;
  }>;
  phone?: string;
  email?: string;
  whatsappNumber?: string;
  address?: string;
  socialLinks?: Array<{
    platform?: "Facebook" | "Instagram" | "LinkedIn" | "YouTube" | "Twitter";
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
};

export type UniversityReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "university";
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  studentName?: string;
  headline?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  university?: UniversityReference;
  course?: CourseReference;
  destination?: DestinationReference;
  quote?: string;
  counsellorName?: string;
  videoUrl?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?:
    | "Country Guide"
    | "Visa Guide"
    | "Scholarship Guide"
    | "Rankings"
    | "Course Comparison"
    | "Student Life"
    | "Career Trends";
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author?: AuthorReference;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  publishedAt?: string;
  seoTitle?: string;
  seoDescription?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
};

export type Scholarship = {
  _id: string;
  _type: "scholarship";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  type?: "Merit" | "Need-based" | "Government" | "Private";
  destination?: DestinationReference;
  university?: UniversityReference;
  amount?: string;
  eligibility?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  deadline?: string;
  applyUrl?: string;
  seoTitle?: string;
  seoDescription?: string;
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?:
    | "Business"
    | "Engineering"
    | "Computer Science"
    | "Artificial Intelligence"
    | "Cyber Security"
    | "Data Science"
    | "Healthcare"
    | "Finance"
    | "Law"
    | "Psychology"
    | "Design";
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  duration?: string;
  tuitionFrom?: string;
  tuitionFromUSD?: number;
  averageSalary?: string;
  demand?: "Low" | "Medium" | "High" | "Very High";
  topUniversities?: Array<
    {
      _key: string;
    } & UniversityReference
  >;
  admissionRequirements?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  careerOutcomes?: Array<string>;
  seoTitle?: string;
  seoDescription?: string;
};

export type ScholarshipReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "scholarship";
};

export type University = {
  _id: string;
  _type: "university";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  galleryImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  destination?: DestinationReference;
  city?: string;
  ranking?: string;
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  keyFacts?: {
    foundedYear?: string;
    type?: string;
    studentStrength?: string;
    internationalStudents?: string;
  };
  courses?: Array<
    {
      _key: string;
    } & CourseReference
  >;
  tuitionFrom?: string;
  tuitionFromUSD?: number;
  feeStructure?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  paymentOptions?: Array<string>;
  scholarshipsAvailable?: boolean;
  scholarships?: Array<
    {
      _key: string;
    } & ScholarshipReference
  >;
  admissionRequirements?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  studentSatisfaction?: string;
  indianCommunity?: {
    studentCount?: string;
    description?: string;
  };
  studentTestimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  accommodation?: {
    onCampus?: string;
    offCampus?: string;
  };
  cityGuide?: {
    overview?: string;
    costOfLiving?: string;
    climate?: string;
    safety?: string;
  };
  nearestAirport?: string;
  airportDistance?: string;
  transportationOptions?: Array<string>;
  seoTitle?: string;
  seoDescription?: string;
};

export type Destination = {
  _id: string;
  _type: "destination";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  country?: string;
  flagEmoji?: string;
  slug?: Slug;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  summary?: string;
  whyStudyPoints?: Array<string>;
  galleryImages?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  overview?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  popularCourses?: Array<
    {
      _key: string;
    } & CourseReference
  >;
  universities?: Array<
    {
      _key: string;
    } & UniversityReference
  >;
  tuitionFees?: string;
  costOfLiving?: string;
  costBreakdownUSD?: {
    tuitionMin?: number;
    tuitionMax?: number;
    accommodationOnCampus?: number;
    accommodationOffCampus?: number;
    foodAndLiving?: number;
    travel?: number;
    healthInsurance?: number;
    visaFees?: number;
    miscellaneous?: number;
  };
  scholarships?: Array<
    {
      _key: string;
    } & ScholarshipReference
  >;
  visaInfo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  visaGuidance?: {
    processSteps?: Array<string>;
    documentsChecklist?: Array<string>;
    timeline?: string;
    financialRequirements?: string;
    commonMistakes?: Array<string>;
    countryTips?: string;
  };
  workRights?: string;
  postStudyOpportunities?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  intakeMonths?: Array<string>;
  applicationDeadlines?: Array<{
    intake?: string;
    opens?: string;
    closes?: string;
    _type: "deadlineWindow";
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageBuilder?: PageBuilder;
  seoTitle?: string;
  seoDescription?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Logo
  | CtaBlock
  | TestimonialReference
  | TestimonialsBlock
  | CourseReference
  | CoursesBlock
  | DestinationReference
  | DestinationsBlock
  | TimelineBlock
  | AboutBlock
  | TrustIndicatorsBlock
  | TrustBlock
  | Features
  | Hero
  | PageBuilder
  | Lead
  | SiteSettings
  | UniversityReference
  | Testimonial
  | SanityImageCrop
  | SanityImageHotspot
  | AuthorReference
  | Post
  | Slug
  | Author
  | Scholarship
  | Course
  | ScholarshipReference
  | University
  | Destination
  | Page
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: "siteSettings";
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  stats?: Array<{
    value?: string;
    label?: string;
    _type: "stat";
    _key: string;
  }>;
  phone?: string;
  email?: string;
  whatsappNumber?: string;
  address?: string;
  socialLinks?: Array<{
    platform?: "Facebook" | "Instagram" | "LinkedIn" | "Twitter" | "YouTube";
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: PAGES_QUERY
// Query: *[_type == "page" && defined(slug.current)] | order(title asc){ _id, title, slug }
export type PAGES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{    _id,    title,    seoTitle,    seoDescription,    pageBuilder[]{      _key,      _type,      ...,      destinations[]->{ _id, country, flagEmoji, slug, summary, heroImage, whyStudyPoints, galleryImages },      courses[]->{        _id,        title,        slug,        category,        duration,        averageSalary,        topUniversities[]->{ _id, destination->{ _id, country, slug } }      },      testimonials[]->{        _id,        studentName,        headline,        photo,        quote,        counsellorName,        videoUrl,        university->{ name },        course->{ title },        destination->{ country }      }    }  }
export type PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  pageBuilder: Array<
    | {
        _key: string;
        _type: "aboutBlock";
        heading?: string;
        mission?: string;
        vision?: string;
        whyFoundedHeading?: string;
        whyFounded?: string;
        coreValues?: Array<{
          title?: string;
          description?: string;
          _type: "coreValue";
          _key: string;
        }>;
        destinations: null;
        courses: null;
        testimonials: null;
      }
    | {
        _key: string;
        _type: "coursesBlock";
        heading?: string;
        courses: Array<{
          _id: string;
          title: string | null;
          slug: Slug | null;
          category:
            | "Artificial Intelligence"
            | "Business"
            | "Computer Science"
            | "Cyber Security"
            | "Data Science"
            | "Design"
            | "Engineering"
            | "Finance"
            | "Healthcare"
            | "Law"
            | "Psychology"
            | null;
          duration: string | null;
          averageSalary: string | null;
          topUniversities: Array<{
            _id: string;
            destination: {
              _id: string;
              country: string | null;
              slug: Slug | null;
            } | null;
          }> | null;
        }> | null;
        destinations: null;
        testimonials: null;
      }
    | {
        _key: string;
        _type: "ctaBlock";
        heading?: string;
        subheading?: string;
        ctaLabel?: string;
        ctaUrl?: string;
        destinations: null;
        courses: null;
        testimonials: null;
      }
    | {
        _key: string;
        _type: "destinationsBlock";
        heading?: string;
        destinations: Array<{
          _id: string;
          country: string | null;
          flagEmoji: string | null;
          slug: Slug | null;
          summary: string | null;
          heroImage: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          } | null;
          whyStudyPoints: Array<string> | null;
          galleryImages: Array<{
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
            _key: string;
          }> | null;
        }> | null;
        courses: null;
        testimonials: null;
      }
    | {
        _key: string;
        _type: "features";
        heading?: string;
        items?: Array<{
          title?: string;
          description?: string;
          _type: "featureItem";
          _key: string;
        }>;
        destinations: null;
        courses: null;
        testimonials: null;
      }
    | {
        _key: string;
        _type: "hero";
        rotatingQuotes?: Array<string>;
        heading?: string;
        subheading?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        ctaLabel?: string;
        ctaUrl?: string;
        secondaryCtaLabel?: string;
        secondaryCtaUrl?: string;
        tertiaryCtaLabel?: string;
        tertiaryCtaUrl?: string;
        destinations: null;
        courses: null;
        testimonials: null;
      }
    | {
        _key: string;
        _type: "testimonialsBlock";
        heading?: string;
        testimonials: Array<{
          _id: string;
          studentName: string | null;
          headline: string | null;
          photo: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          } | null;
          quote: string | null;
          counsellorName: string | null;
          videoUrl: string | null;
          university: {
            name: string | null;
          } | null;
          course: {
            title: string | null;
          } | null;
          destination: {
            country: string | null;
          } | null;
        }> | null;
        destinations: null;
        courses: null;
      }
    | {
        _key: string;
        _type: "timelineBlock";
        heading?: string;
        milestones?: Array<{
          year?: string;
          description?: string;
          _type: "milestone";
          _key: string;
        }>;
        futureVisionHeading?: string;
        futureVision?: string;
        destinations: null;
        courses: null;
        testimonials: null;
      }
    | {
        _key: string;
        _type: "trustBlock";
        heading?: string;
        items?: Array<{
          title?: string;
          description?: string;
          _type: "trustItem";
          _key: string;
        }>;
        destinations: null;
        courses: null;
        testimonials: null;
      }
    | {
        _key: string;
        _type: "trustIndicatorsBlock";
        heading?: string;
        trustLine?: string;
        stats?: Array<{
          value?: string;
          label?: string;
          _type: "trustStat";
          _key: string;
        }>;
        partnerLogos?: Array<{
          name?: string;
          logo?: Logo;
          _type: "partnerLogo";
          _key: string;
        }>;
        awards?: Array<string>;
        testimonials: Array<{
          _id: string;
          studentName: string | null;
          headline: string | null;
          photo: {
            asset?: SanityImageAssetReference;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            _type: "image";
          } | null;
          quote: string | null;
          counsellorName: string | null;
          videoUrl: string | null;
          university: {
            name: string | null;
          } | null;
          course: {
            title: string | null;
          } | null;
          destination: {
            country: string | null;
          } | null;
        }> | null;
        destinations: null;
        courses: null;
      }
  > | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: DESTINATIONS_QUERY
// Query: *[_type == "destination"] | order(country asc){ _id, country, flagEmoji, slug, summary, heroImage, whyStudyPoints, galleryImages }
export type DESTINATIONS_QUERY_RESULT = Array<{
  _id: string;
  country: string | null;
  flagEmoji: string | null;
  slug: Slug | null;
  summary: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  whyStudyPoints: Array<string> | null;
  galleryImages: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: DESTINATION_QUERY
// Query: *[_type == "destination" && slug.current == $slug][0]{    _id,    country,    flagEmoji,    slug,    heroImage,    summary,    whyStudyPoints,    overview,    tuitionFees,    costOfLiving,    visaInfo,    visaGuidance,    workRights,    postStudyOpportunities,    intakeMonths,    seoTitle,    seoDescription,    popularCourses[]->{ _id, title, slug, category },    universities[]->{ _id, name, slug, logo, city, ranking },    scholarships[]->{ _id, name, slug, type, amount, deadline }  }
export type DESTINATION_QUERY_RESULT = {
  _id: string;
  country: string | null;
  flagEmoji: string | null;
  slug: Slug | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  summary: string | null;
  whyStudyPoints: Array<string> | null;
  overview: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  tuitionFees: string | null;
  costOfLiving: string | null;
  visaInfo: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  visaGuidance: {
    processSteps?: Array<string>;
    documentsChecklist?: Array<string>;
    timeline?: string;
    financialRequirements?: string;
    commonMistakes?: Array<string>;
    countryTips?: string;
  } | null;
  workRights: string | null;
  postStudyOpportunities: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  intakeMonths: Array<string> | null;
  seoTitle: string | null;
  seoDescription: string | null;
  popularCourses: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    category:
      | "Artificial Intelligence"
      | "Business"
      | "Computer Science"
      | "Cyber Security"
      | "Data Science"
      | "Design"
      | "Engineering"
      | "Finance"
      | "Healthcare"
      | "Law"
      | "Psychology"
      | null;
  }> | null;
  universities: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    city: string | null;
    ranking: string | null;
  }> | null;
  scholarships: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    type: "Government" | "Merit" | "Need-based" | "Private" | null;
    amount: string | null;
    deadline: string | null;
  }> | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: VISA_GUIDANCE_INDEX_QUERY
// Query: *[_type == "destination" && defined(visaGuidance)] | order(country asc){    _id,    country,    flagEmoji,    slug,    visaGuidance  }
export type VISA_GUIDANCE_INDEX_QUERY_RESULT = Array<{
  _id: string;
  country: string | null;
  flagEmoji: string | null;
  slug: Slug | null;
  visaGuidance: {
    processSteps?: Array<string>;
    documentsChecklist?: Array<string>;
    timeline?: string;
    financialRequirements?: string;
    commonMistakes?: Array<string>;
    countryTips?: string;
  };
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: INTAKE_CALENDAR_QUERY
// Query: *[_type == "destination" && (defined(intakeMonths) || defined(applicationDeadlines))] | order(country asc){    _id,    country,    flagEmoji,    intakeMonths,    applicationDeadlines  }
export type INTAKE_CALENDAR_QUERY_RESULT = Array<{
  _id: string;
  country: string | null;
  flagEmoji: string | null;
  intakeMonths: Array<string> | null;
  applicationDeadlines: Array<{
    intake?: string;
    opens?: string;
    closes?: string;
    _type: "deadlineWindow";
    _key: string;
  }> | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: COST_CALCULATOR_QUERY
// Query: *[_type == "destination" && defined(costBreakdownUSD)] | order(country asc){    _id,    country,    flagEmoji,    costBreakdownUSD,    universities[]->{ _id, name }  }
export type COST_CALCULATOR_QUERY_RESULT = Array<{
  _id: string;
  country: string | null;
  flagEmoji: string | null;
  costBreakdownUSD: {
    tuitionMin?: number;
    tuitionMax?: number;
    accommodationOnCampus?: number;
    accommodationOffCampus?: number;
    foodAndLiving?: number;
    travel?: number;
    healthInsurance?: number;
    visaFees?: number;
    miscellaneous?: number;
  };
  universities: Array<{
    _id: string;
    name: string | null;
  }> | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: UNIVERSITIES_QUERY
// Query: *[_type == "university"] | order(name asc){    _id,    name,    slug,    logo,    city,    ranking,    tuitionFrom,    tuitionFromUSD,    destination->{ _id, country, slug, intakeMonths },    courses[]->{ _id, title, demand }  }
export type UNIVERSITIES_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  city: string | null;
  ranking: string | null;
  tuitionFrom: string | null;
  tuitionFromUSD: number | null;
  destination: {
    _id: string;
    country: string | null;
    slug: Slug | null;
    intakeMonths: Array<string> | null;
  } | null;
  courses: Array<{
    _id: string;
    title: string | null;
    demand: "High" | "Low" | "Medium" | "Very High" | null;
  }> | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: UNIVERSITY_QUERY
// Query: *[_type == "university" && slug.current == $slug][0]{    _id,    name,    slug,    logo,    heroImage,    galleryImages,    city,    ranking,    overview,    keyFacts,    tuitionFrom,    feeStructure,    paymentOptions,    scholarshipsAvailable,    admissionRequirements,    studentSatisfaction,    indianCommunity,    accommodation,    cityGuide,    nearestAirport,    airportDistance,    transportationOptions,    seoTitle,    seoDescription,    destination->{ _id, country, slug },    courses[]->{ _id, title, slug, category, duration },    scholarships[]->{ _id, name, slug, type, amount },    studentTestimonials[]->{      _id,      studentName,      headline,      photo,      quote,      counsellorName,      videoUrl,      university->{ name },      course->{ title },      destination->{ country }    }  }
export type UNIVERSITY_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  galleryImages: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  city: string | null;
  ranking: string | null;
  overview: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  keyFacts: {
    foundedYear?: string;
    type?: string;
    studentStrength?: string;
    internationalStudents?: string;
  } | null;
  tuitionFrom: string | null;
  feeStructure: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  paymentOptions: Array<string> | null;
  scholarshipsAvailable: boolean | null;
  admissionRequirements: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  studentSatisfaction: string | null;
  indianCommunity: {
    studentCount?: string;
    description?: string;
  } | null;
  accommodation: {
    onCampus?: string;
    offCampus?: string;
  } | null;
  cityGuide: {
    overview?: string;
    costOfLiving?: string;
    climate?: string;
    safety?: string;
  } | null;
  nearestAirport: string | null;
  airportDistance: string | null;
  transportationOptions: Array<string> | null;
  seoTitle: string | null;
  seoDescription: string | null;
  destination: {
    _id: string;
    country: string | null;
    slug: Slug | null;
  } | null;
  courses: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    category:
      | "Artificial Intelligence"
      | "Business"
      | "Computer Science"
      | "Cyber Security"
      | "Data Science"
      | "Design"
      | "Engineering"
      | "Finance"
      | "Healthcare"
      | "Law"
      | "Psychology"
      | null;
    duration: string | null;
  }> | null;
  scholarships: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    type: "Government" | "Merit" | "Need-based" | "Private" | null;
    amount: string | null;
  }> | null;
  studentTestimonials: Array<{
    _id: string;
    studentName: string | null;
    headline: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    quote: string | null;
    counsellorName: string | null;
    videoUrl: string | null;
    university: {
      name: string | null;
    } | null;
    course: {
      title: string | null;
    } | null;
    destination: {
      country: string | null;
    } | null;
  }> | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course"] | order(title asc){    _id,    title,    slug,    category,    duration,    tuitionFrom,    tuitionFromUSD,    averageSalary,    demand,    careerOutcomes,    topUniversities[]->{      _id,      name,      slug,      studentSatisfaction,      destination->{ _id, country, slug, intakeMonths }    }  }
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  category:
    | "Artificial Intelligence"
    | "Business"
    | "Computer Science"
    | "Cyber Security"
    | "Data Science"
    | "Design"
    | "Engineering"
    | "Finance"
    | "Healthcare"
    | "Law"
    | "Psychology"
    | null;
  duration: string | null;
  tuitionFrom: string | null;
  tuitionFromUSD: number | null;
  averageSalary: string | null;
  demand: "High" | "Low" | "Medium" | "Very High" | null;
  careerOutcomes: Array<string> | null;
  topUniversities: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    studentSatisfaction: string | null;
    destination: {
      _id: string;
      country: string | null;
      slug: Slug | null;
      intakeMonths: Array<string> | null;
    } | null;
  }> | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: COURSE_QUERY
// Query: *[_type == "course" && slug.current == $slug][0]{    _id,    title,    slug,    category,    overview,    duration,    averageSalary,    demand,    admissionRequirements,    careerOutcomes,    seoTitle,    seoDescription,    topUniversities[]->{ _id, name, slug, city, destination->{ country } }  }
export type COURSE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  category:
    | "Artificial Intelligence"
    | "Business"
    | "Computer Science"
    | "Cyber Security"
    | "Data Science"
    | "Design"
    | "Engineering"
    | "Finance"
    | "Healthcare"
    | "Law"
    | "Psychology"
    | null;
  overview: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  duration: string | null;
  averageSalary: string | null;
  demand: "High" | "Low" | "Medium" | "Very High" | null;
  admissionRequirements: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  careerOutcomes: Array<string> | null;
  seoTitle: string | null;
  seoDescription: string | null;
  topUniversities: Array<{
    _id: string;
    name: string | null;
    slug: Slug | null;
    city: string | null;
    destination: {
      country: string | null;
    } | null;
  }> | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: SCHOLARSHIPS_QUERY
// Query: *[_type == "scholarship"] | order(deadline asc){    _id,    name,    slug,    type,    amount,    deadline,    destination->{ country },    university->{ name }  }
export type SCHOLARSHIPS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  type: "Government" | "Merit" | "Need-based" | "Private" | null;
  amount: string | null;
  deadline: string | null;
  destination: {
    country: string | null;
  } | null;
  university: {
    name: string | null;
  } | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc){    _id,    title,    slug,    category,    excerpt,    coverImage,    publishedAt,    author->{ name, photo }  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  category:
    | "Career Trends"
    | "Country Guide"
    | "Course Comparison"
    | "Rankings"
    | "Scholarship Guide"
    | "Student Life"
    | "Visa Guide"
    | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  publishedAt: string | null;
  author: {
    name: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: ../web/src/sanity/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    category,    excerpt,    coverImage,    body,    publishedAt,    seoTitle,    seoDescription,    author->{ name, photo, bio }  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  category:
    | "Career Trends"
    | "Country Guide"
    | "Course Comparison"
    | "Rankings"
    | "Scholarship Guide"
    | "Student Life"
    | "Visa Guide"
    | null;
  excerpt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  publishedAt: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  author: {
    name: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
  } | null;
} | null;

// Source: ../web/src/sanity/queries.ts
// Variable: LEAD_FORM_OPTIONS_QUERY
// Query: {    "countries": *[_type == "destination"] | order(country asc).country,    "courses": *[_type == "course"] | order(title asc).title  }
export type LEAD_FORM_OPTIONS_QUERY_RESULT = {
  countries: Array<string | null>;
  courses: Array<string | null>;
};

// Source: ../web/src/sanity/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"]{    _id,    studentName,    headline,    photo,    quote,    counsellorName,    videoUrl,    university->{ name },    course->{ title },    destination->{ country }  }
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  studentName: string | null;
  headline: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  quote: string | null;
  counsellorName: string | null;
  videoUrl: string | null;
  university: {
    name: string | null;
  } | null;
  course: {
    title: string | null;
  } | null;
  destination: {
    country: string | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings" && _id == "siteSettings"][0]': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "page" && defined(slug.current)] | order(title asc){ _id, title, slug }': PAGES_QUERY_RESULT;
    '*[_type == "page" && slug.current == $slug][0]{\n    _id,\n    title,\n    seoTitle,\n    seoDescription,\n    pageBuilder[]{\n      _key,\n      _type,\n      ...,\n      destinations[]->{ _id, country, flagEmoji, slug, summary, heroImage, whyStudyPoints, galleryImages },\n      courses[]->{\n        _id,\n        title,\n        slug,\n        category,\n        duration,\n        averageSalary,\n        topUniversities[]->{ _id, destination->{ _id, country, slug } }\n      },\n      testimonials[]->{\n        _id,\n        studentName,\n        headline,\n        photo,\n        quote,\n        counsellorName,\n        videoUrl,\n        university->{ name },\n        course->{ title },\n        destination->{ country }\n      }\n    }\n  }': PAGE_QUERY_RESULT;
    '*[_type == "destination"] | order(country asc){ _id, country, flagEmoji, slug, summary, heroImage, whyStudyPoints, galleryImages }': DESTINATIONS_QUERY_RESULT;
    '*[_type == "destination" && slug.current == $slug][0]{\n    _id,\n    country,\n    flagEmoji,\n    slug,\n    heroImage,\n    summary,\n    whyStudyPoints,\n    overview,\n    tuitionFees,\n    costOfLiving,\n    visaInfo,\n    visaGuidance,\n    workRights,\n    postStudyOpportunities,\n    intakeMonths,\n    seoTitle,\n    seoDescription,\n    popularCourses[]->{ _id, title, slug, category },\n    universities[]->{ _id, name, slug, logo, city, ranking },\n    scholarships[]->{ _id, name, slug, type, amount, deadline }\n  }': DESTINATION_QUERY_RESULT;
    '*[_type == "destination" && defined(visaGuidance)] | order(country asc){\n    _id,\n    country,\n    flagEmoji,\n    slug,\n    visaGuidance\n  }': VISA_GUIDANCE_INDEX_QUERY_RESULT;
    '*[_type == "destination" && (defined(intakeMonths) || defined(applicationDeadlines))] | order(country asc){\n    _id,\n    country,\n    flagEmoji,\n    intakeMonths,\n    applicationDeadlines\n  }': INTAKE_CALENDAR_QUERY_RESULT;
    '*[_type == "destination" && defined(costBreakdownUSD)] | order(country asc){\n    _id,\n    country,\n    flagEmoji,\n    costBreakdownUSD,\n    universities[]->{ _id, name }\n  }': COST_CALCULATOR_QUERY_RESULT;
    '*[_type == "university"] | order(name asc){\n    _id,\n    name,\n    slug,\n    logo,\n    city,\n    ranking,\n    tuitionFrom,\n    tuitionFromUSD,\n    destination->{ _id, country, slug, intakeMonths },\n    courses[]->{ _id, title, demand }\n  }': UNIVERSITIES_QUERY_RESULT;
    '*[_type == "university" && slug.current == $slug][0]{\n    _id,\n    name,\n    slug,\n    logo,\n    heroImage,\n    galleryImages,\n    city,\n    ranking,\n    overview,\n    keyFacts,\n    tuitionFrom,\n    feeStructure,\n    paymentOptions,\n    scholarshipsAvailable,\n    admissionRequirements,\n    studentSatisfaction,\n    indianCommunity,\n    accommodation,\n    cityGuide,\n    nearestAirport,\n    airportDistance,\n    transportationOptions,\n    seoTitle,\n    seoDescription,\n    destination->{ _id, country, slug },\n    courses[]->{ _id, title, slug, category, duration },\n    scholarships[]->{ _id, name, slug, type, amount },\n    studentTestimonials[]->{\n      _id,\n      studentName,\n      headline,\n      photo,\n      quote,\n      counsellorName,\n      videoUrl,\n      university->{ name },\n      course->{ title },\n      destination->{ country }\n    }\n  }': UNIVERSITY_QUERY_RESULT;
    '*[_type == "course"] | order(title asc){\n    _id,\n    title,\n    slug,\n    category,\n    duration,\n    tuitionFrom,\n    tuitionFromUSD,\n    averageSalary,\n    demand,\n    careerOutcomes,\n    topUniversities[]->{\n      _id,\n      name,\n      slug,\n      studentSatisfaction,\n      destination->{ _id, country, slug, intakeMonths }\n    }\n  }': COURSES_QUERY_RESULT;
    '*[_type == "course" && slug.current == $slug][0]{\n    _id,\n    title,\n    slug,\n    category,\n    overview,\n    duration,\n    averageSalary,\n    demand,\n    admissionRequirements,\n    careerOutcomes,\n    seoTitle,\n    seoDescription,\n    topUniversities[]->{ _id, name, slug, city, destination->{ country } }\n  }': COURSE_QUERY_RESULT;
    '*[_type == "scholarship"] | order(deadline asc){\n    _id,\n    name,\n    slug,\n    type,\n    amount,\n    deadline,\n    destination->{ country },\n    university->{ name }\n  }': SCHOLARSHIPS_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)] | order(publishedAt desc){\n    _id,\n    title,\n    slug,\n    category,\n    excerpt,\n    coverImage,\n    publishedAt,\n    author->{ name, photo }\n  }': POSTS_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    category,\n    excerpt,\n    coverImage,\n    body,\n    publishedAt,\n    seoTitle,\n    seoDescription,\n    author->{ name, photo, bio }\n  }': POST_QUERY_RESULT;
    '{\n    "countries": *[_type == "destination"] | order(country asc).country,\n    "courses": *[_type == "course"] | order(title asc).title\n  }': LEAD_FORM_OPTIONS_QUERY_RESULT;
    '*[_type == "testimonial"]{\n    _id,\n    studentName,\n    headline,\n    photo,\n    quote,\n    counsellorName,\n    videoUrl,\n    university->{ name },\n    course->{ title },\n    destination->{ country }\n  }': TESTIMONIALS_QUERY_RESULT;
  }
}
